server:
  port: 9001

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-server-id
          uri: lb://user-server   #://localhost:8081
          predicates:
            - Path=/user/**
        - id: discussPost-server-id
          uri: lb://discussPost-server
          predicates:
            - Path=/discussPost/**,/comment/**
        - id: like-server
          uri: lb://follow-server
          predicates:
            - Path=/follow/**,/like/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



management:
  endpoints:
    web:
      exposure:
        include: '*'

