server:
  port: 8083

spring:
  application:
    name: follow-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  # thymeleaf
  thymeleaf:
    cache: false
  redis:
    database: 1
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true


